#[botdetection.ip_limit]
# activate link_token method in the ip_limit method
#link_token = false



[real_ip]
x_for = 1
ipv4_prefix = 32
ipv6_prefix = 48

[botdetection.ip_limit]
filter_link_local = false
link_token = false

[botdetection.ip_lists]
block_ip = []
pass_ip = [ "0.0.0.0/0", "::/0" ]  # Allows all Ipv4,IPv6 addresses
pass_searxng_org = true